apiVersion: v1
kind: Service
metadata:
  name: {{ include "next13-demo.fullname" . }}
  namespace: next13-demo
  labels:
    {{- include "next13-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "next13-demo.selectorLabels" . | nindent 4 }}
