apiVersion: v1
kind: Service
metadata:
  name: { { include "cluster-yeoul.fullname" . } }
  labels: { { - include "cluster-yeoul.labels" . | nindent 4 } }
spec:blue-hope
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "cluster-yeoul.selectorLabels" . | nindent 4 } }
blue-hopeblue-hopeblue-hopeblue-hopeblue-hope