apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-cd
  namespace: istio-ingress
spec:
  hosts:
    - "argo-cd.yourdomain.com"
  gateways:
    - istio-ingress/gateway-prod
  http:
    - route:
        - destination:
            host: argo-argocd-server.argo-cd.svc.cluster.local
